### ISSUE TITLE
[Request] Add Arctic Horizon to Matrix repo

### ISSUE THREAD

**Issue by FunctionalHacker** [jurialmunkey/repository.jurialmunkey#17]
Hi, I just installed Arctic Horizon on Kodi 19.0-RC1 using [this patch](https://github.com/jurialmunkey/skin.arctic.horizon/pull/207/commits/93add64d99a9fddaff2b3d8ef0e8d3909f6a3628) and everything seems to be working fine. Would it be possible to get this skin, and possibly Zephyr 2 too on this repository? Would certainly make it easier to install and update.

**Comment by jurialmunkey** [comment]
There's no Matrix version of AH available yet. A Matrix version will be coming soon.

There are skinning engine changes that need to be accommodated - installing it via a patch to xbmcgui will likely work in most instances since there are no major breaking changes. However, there will be some places where minor things will break and so I will only add it to the repo after I've officially made those changes.

AZ2 won't have a Matrix version as it is no longer developed.

**Comment by drinfernoo** [comment]
Arctic Horizon (0.5.59) has now been added to the Matrix repo.
