### ISSUE TITLE
[Meta] Steps to update repository

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/repository.jurialmunkey#2]
@drinfernoo - Can you run me through the steps to update the repo? I'll leave the responsibility to update mostly to you, but it would be useful to know in case I need to push a critical update out.

It looks relatively simple, but I want to make sure I'm following a set procedure to avoid any messiness. Also, should I notify you in some way if I do make an update to the repo, or will you just remember to do a git pull before making updates?

**Comment by drinfernoo** [comment]
The basic process is that a source folder for each add-on needs to be placed in the root (which I'm keeping backups of, and removing before I push), and then run the script. There's some incompatibility with the skin source folder and my script, which I haven't nailed down yet, so *that one* I'm having to zip manually, and add it's content to the `addons.xml`, but I'll hopefully get that nailed down very soon. I get notified through GitHub whenever you push, so I've been trying to stay up to date, though 👍

**Comment by jurialmunkey** [comment]
Ah okay, so it's still just a manual process at the moment for updating the skin. I'll hold-off until the script is functional!

Also, thanks again for doing all this. I really appreciate it! 😁

**Comment by drinfernoo** [comment]
Honestly, I'm honored 😁 My main skins ever since I find Kodi have been AZ, and then Aura, and I'm gonna be switching to AZ2 very soon. I'd love to help with anything I can.

**Comment by drinfernoo** [comment]
I've finally fixed the generator script! From now on, this should be relatively simple to make work, so here are the steps:

1. Copy a source directory for each desired add-on into the root of this project. For the time being, these include *this* repo (which is contained in itself), [Horizon Genre Icons](https://github.com/Swageroni/resource.images.moviegenreicons.horizon) (which you can clone to get the folder), [Marcelveldt's Repo](https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/repository.marcelveldt/repository.marcelveldt-1.0.1.zip) (which you can simply unzip), the [Rector Stuff repo](https://github.com/rmrector/repository.rector.stuff/raw/master/latest/repository.rector.stuff-latest.zip) (which you can unzip), and Arctic Zephyr 2.

These folders are used by the script to generate zipped versions and to generate the repository metadata files `addons.xml` and `addons.xml.md5`.

2. Run `_repo_xml_generator.py`.

This does all the heavy lifting of creating zips of each add-on, structuring the folders correctly, and creating the `addons.xml` and `addons.xml.md5` files correctly, in order to have the repo function inside Kodi.

3. Delete those source folders, excluding the one for this repo, and perform a git commit/push.

The reasoning for this is simply to not have physical copies of each add-on contained *in* this repository They *can* be left alone if desired, but I feel like it makes a mess of the repo.

The changes should be reflected in Kodi almost instantly for users with the repo installed, but it may require a restart of Kodi.
