### ISSUE TITLE
[Meta] Remove TMDbHelper?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/repository.jurialmunkey#6]
I've seen some movement regarding the addition of plugin.video.themoviedbhelper to the official Kodi repository. At that point, should I remove it from this repo? Or leave it in here for "test" releases?

**Comment by drinfernoo** [comment]
Congratulations! They merged the PR (https://github.com/xbmc/repo-plugins/commit/1eb4ba03b5cb43f7cd07219917c42185f9b8fa79) :smile: Should I remove this add-on from the repo now?

**Comment by jurialmunkey** [comment]
Hey sorry - I completely missed this issue for some reason.

You've already guessed my answer anyway since you've updated it. I think keeping the most up to date version in this repo as a type of bleeding-edge beta release is probably a good idea - that way users can choose between the most recent version and the stable kodi repo version.

Which, coincidentally, is why this version is considerably ahead of the Kodi repo - because I want to make sure I get all the bugs ironed out before PR to official for code review.
