### ISSUE TITLE
[Meta] Matrix Repository

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/repository.jurialmunkey#9]
I'm attempting to do something like as seen here: https://forum.kodi.tv/showthread.php?tid=310315, https://forum.kodi.tv/showthread.php?tid=273588&, or https://github.com/OpenELEQ/repository.q

Basically, this type of structure would allow the repo to serve different versions of your add-ons to Leia and Matrix, respectively. I've begun this work on the `matrix` branch of this repo... but it doesn't seem to work quite right. No matter what I try, it seems to only want to install the Leia versions in Matrix, anyways.

Mainly I'm just trying to get this ready for the future, but if I can get it working, I don't see why it couldn't be used now, as there are certainly users that are trying to migrate to Matrix already. Can you see what I'm missing?

**Comment by jurialmunkey** [comment]
Honestly, I don't really know. You're the pro when it comes to the repo stuff!

There's a reason why I haven't maintained a repo in the past, and that reason is that I haven't ever been able to get it to work properly...  

I do know that multidir support was dropped for a while in Krypton but then was added back in https://github.com/xbmc/xbmc/pull/10059

But I think since that discussion it has been kept in.

**Comment by drinfernoo** [comment]
So... that was a bit enlightening. Seems that the version numbers will need to be different, but that it can be done. What a pain... I know you had mentioned just waiting until Matrix was closer to stable, and that's probably the best bet, I guess.

**Comment by jurialmunkey** [comment]
Does it need to have something like `~matrix` added to the end of the version or something like that? Because if that's all it needs, it's pretty easy for me to maintain that it in the separate matrix branch as it should still work to merge version commits from master.

e.g. 
if master is 
`0.2.1` going to `0.2.2`

and matrix is 
`0.2.1~matrix`
then merging the commit from master into the matrix branch should work automatically to go to `0.2.2~matrix`

**Comment by drinfernoo** [comment]
Really, I'm not sure. I just ran a couple of tests, but it doesn't seem like even that is making it work the way I expect. Not really sure, but I'll table it for now.

**Comment by drinfernoo** [comment]
Well, I didn't get it working with the fancy multidir stuff yet, but I've created a `matrix` branch, and there are now two versions (for Leia and Matrix, respectively) of the repo, both available in this repository's root. I can now successfully install any applicable add-ons in Matrix, without relying on installing from GitHub versions,

Users who already have the repo installed in Matrix will need to manually update it from zip in order to continue properly getting updates.
